apiVersion: apps/v1
kind: Deployment
metadata:
  name: spirit-dns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spirit-dns
  template:
    metadata:
      labels:
        app: spirit-dns
    spec:
      containers:
        - name: spirit-dns
          image: us-west1-docker.pkg.dev/adept-coda-415809/spirit-dns:latest
          ports:
            - containerPort: 8080